version: '0.1'

services:
  db:
    image: mysql:8.0
    container_name: db
    environment:
      - MYSQL_DATABASE=metabase-db
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=admin
    restart: always
    volumes:
      - db-data:/var/lib/mysql
      - ./mysql:/home/
    command: --default-authentication-plugin=mysql_native_password
    expose:
      - 3306

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    environment:
      - MB_DB_FILE=/metabase-data/metabase.db
      - MB_DB_TYPE=mysql
      - MB_DB_DBNAME=metabase-db
      - MB_DB_PORT=3306
      - MB_DB_USER=user
      - MB_DB_HOST=db
      - MB_DB_PASS=password
      - JAVA_TIMEZONE=America/Buenos_Aires
    ports:
      - 3000:3000
    volumes:
      - mb-data:/metabase-data
    depends_on:
      - db
  
  rstudio:
    build: ./rstudio
    image: statistics-playground/rstudio
    container_name: rstudio
    restart: always
    ports:
      - 8787:8787
    environment:
      - ROOT=true
      - DISABLE_AUTH=true
    volumes:
      - rstudio-data:/home/rstudio/.config/rstudio
      - r-data:/usr/local/lib/R
      - ./rstudio:/home/rstudio

  jupyter:
    image: jupyter/datascience-notebook
    container_name: jupyter
    restart: always
    ports:
      - 8888:8888
      - 4200:4200
    user: root
    environment:
      - NB_USER=user
      - PASSWORD=password
      - CHOWN_HOME=yes
      - GRANT_SUDO=yes
      - RESTARTABLE=yes
      - JUPYTER_ENABLE_LAB=yes
    volumes:
      - ./jupyter:/home/user
    command: "start-notebook.sh --NotebookApp.token='' --NotebookApp.password=''"
    expose:
      - 4200

  redis:
    image: redis/redis-stack
    container_name: redis
    restart: always
    ports:
      - 6379:6379
      - 8001:8001
    volumes:
      - ./redis/data:/data
    expose:
      - 6379
      - 8001
  
  mongo:
    image: mongo
    container_name: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=pass
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
    healthcheck:
      test: echo 'db.runCommand("ping").ok' | mongosh mongo:27017/test --quiet
      timeout: 10s
      retries: 2
      start_period: 10s

  mongoadmin:
    image: mongo-express
    container_name: mongo-express
    restart: on-failure
    depends_on:
      mongo:
        condition: service_healthy
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=1234
    ports:
      - 8081:8081

  mindsdb:
    image: mindsdb/mindsdb
    container_name: mindsdb
    restart: always
    ports:
      - 47334:47334
      - 47335:47335

  fastapi:
    build: ./fastapi
    container_name: fastapi
    image: statistics-playground/fastapi
    restart: always
    ports:
      - 80:80
    expose:
      - 80
    
volumes:
  db-data:
  mb-data:
  rstudio-data:
  r-data: